[package]
name = "rustos"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
sbi-rt = {version = "0.0.3",features = ["legacy"]}

[profile.release]
debug = true